"""Improve all tables. Add user table.

Revision ID: 0d1bffb1cce8
Revises: f1ddd87d6062
Create Date: 2026-05-20 19:47:58.658118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d1bffb1cce8'
down_revision: Union[str, Sequence[str], None] = 'f1ddd87d6062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usertable',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usertable_email'), 'usertable', ['email'], unique=False)
    op.create_index(op.f('ix_usertable_first_name'), 'usertable', ['first_name'], unique=False)
    op.add_column('accounttable', sa.Column('amount', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('accounttable', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('accounttable', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.create_foreign_key(None, 'accounttable', 'usertable', ['user_id'], ['id'])
    op.drop_column('accounttable', 'balance')
    op.add_column('categorytable', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('categorytable', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.create_foreign_key(None, 'categorytable', 'usertable', ['user_id'], ['id'])
    op.add_column('debttable', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('debttable', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.create_foreign_key(None, 'debttable', 'usertable', ['user_id'], ['id'])
    op.add_column('obligationtable', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('obligationtable', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.create_foreign_key(None, 'obligationtable', 'usertable', ['user_id'], ['id'])
    op.add_column('transactiontable', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('transactiontable', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.create_foreign_key(None, 'transactiontable', 'usertable', ['user_id'], ['id'])
    op.drop_column('transactiontable', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactiontable', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactiontable', type_='foreignkey')
    op.drop_column('transactiontable', 'created_at')
    op.drop_column('transactiontable', 'user_id')
    op.drop_constraint(None, 'obligationtable', type_='foreignkey')
    op.drop_column('obligationtable', 'created_at')
    op.drop_column('obligationtable', 'user_id')
    op.drop_constraint(None, 'debttable', type_='foreignkey')
    op.drop_column('debttable', 'created_at')
    op.drop_column('debttable', 'user_id')
    op.drop_constraint(None, 'categorytable', type_='foreignkey')
    op.drop_column('categorytable', 'created_at')
    op.drop_column('categorytable', 'user_id')
    op.add_column('accounttable', sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'accounttable', type_='foreignkey')
    op.drop_column('accounttable', 'created_at')
    op.drop_column('accounttable', 'user_id')
    op.drop_column('accounttable', 'amount')
    op.drop_index(op.f('ix_usertable_first_name'), table_name='usertable')
    op.drop_index(op.f('ix_usertable_email'), table_name='usertable')
    op.drop_table('usertable')
    # ### end Alembic commands ###
