"""Uptade 'hashed_password' to 'password'

Revision ID: 8088536a2b46
Revises: 2613dfc48c40
Create Date: 2026-05-21 19:25:48.759399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8088536a2b46'
down_revision: Union[str, Sequence[str], None] = '2613dfc48c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertable', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False, server_default='secret'))
    op.drop_column('usertable', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertable', sa.Column('hashed_password', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('usertable', 'password')
    # ### end Alembic commands ###
