"""Initialize tables

Revision ID: f1ddd87d6062
Revises: 
Create Date: 2026-05-20 15:03:38.370367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f1ddd87d6062'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounttable',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('profit_percentage', sa.Float(), nullable=False),
    sa.Column('currency', sa.Enum('COP', 'USD', 'CAD', 'CL', name='currency'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounttable_name'), 'accounttable', ['name'], unique=False)
    op.create_table('categorytable',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debttable',
    sa.Column('person_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('LEND', 'BORROW', name='debttype'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_settled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debttable_person_name'), 'debttable', ['person_name'], unique=False)
    op.create_table('obligationtable',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligationtable_name'), 'obligationtable', ['name'], unique=False)
    op.create_table('transactiontable',
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('t_type', sa.Enum('INCOME', 'EXPENSE', name='transactiontype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('caterogy_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounttable.id'], ),
    sa.ForeignKeyConstraint(['caterogy_id'], ['categorytable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactiontable')
    op.drop_index(op.f('ix_obligationtable_name'), table_name='obligationtable')
    op.drop_table('obligationtable')
    op.drop_index(op.f('ix_debttable_person_name'), table_name='debttable')
    op.drop_table('debttable')
    op.drop_table('categorytable')
    op.drop_index(op.f('ix_accounttable_name'), table_name='accounttable')
    op.drop_table('accounttable')
    # ### end Alembic commands ###
