"""Change 'created_at' field onto Transaction table.

Revision ID: fa93580a27b1
Revises: 0d1bffb1cce8
Create Date: 2026-05-20 20:58:16.694759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fa93580a27b1'
down_revision: Union[str, Sequence[str], None] = '0d1bffb1cce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactiontable', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('transactiontable_caterogy_id_fkey'), 'transactiontable', type_='foreignkey')
    op.create_foreign_key(None, 'transactiontable', 'categorytable', ['category_id'], ['id'])
    op.drop_column('transactiontable', 'caterogy_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactiontable', sa.Column('caterogy_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactiontable', type_='foreignkey')
    op.create_foreign_key(op.f('transactiontable_caterogy_id_fkey'), 'transactiontable', 'categorytable', ['caterogy_id'], ['id'])
    op.drop_column('transactiontable', 'category_id')
    # ### end Alembic commands ###
